### PR TITLE
Replace Install and Uninstall with azule-functions

### PR DESCRIPTION
**Pull request by nicknitewolf**
Requires a wiki update

### CODE REVIEW

**Comment by nicknitewolf** [comment]
# **Installation**

## **MacOS**

### 1. Install [Xcode](https://apps.apple.com/us/app/xcode/id497799835)

### 2. Set the $AZULE environment variable, add azule and update-azule to your $PATH

For zsh and bash, open ~/.zprofile and ~/.profile respectively and add the following:

```
# Azule
export AZULE=~/Azule

# add azule commands to path
if [ -d "$HOME/Azule" ] ; then
    PATH="$HOME/Azule:$PATH"
fi
```

For fish, run the following commands:
```
set -gx AZULE ~/Azule
set -U fish_user_paths ~/Azule $fish_user_paths
```

Note: For changes to take effect, you have to restart your terminal.

### 3. Clone and setup Azule
```
git clone https://github.com/Al4ise/Azule $AZULE
$AZULE/setup-azule
```

## **Linux/WSL**
Confirmed to work on Debian

### 1. Set the $AZULE environment variable, add azule and update-azule to your $PATH

For zsh and bash, open ~/.zprofile and ~/.profile respectively and add the following:

```
# Azule
export AZULE=~/Azule

# add azule commands to path
if [ -d "$HOME/Azule" ] ; then
    PATH="$HOME/Azule:$PATH"
fi
```

For fish, run the following commands:
```
set -gx AZULE ~/Azule
set -U fish_user_paths ~/Azule $fish_user_paths
```

Note: For changes to take effect, you have to restart your terminal.

### 2. Dependencies
Make sure all the listed dependencies are installed:
`jq git curl rsync xz-utils unzip zip zstd`

On Debian-based systems, you can run
`sudo apt install jq git curl rsync xz-utils unzip zip zstd`

### 3. Cloning and Setting Up Azule
```
git clone https://github.com/Al4ise/Azule $AZULE
$AZULE/setup-azule
```

## **iOS**

### Download and Install the deb from [Releases](https://github.com/Al4ise/Azule/releases/latest) on your iOS device

## **Uninstall for MacOS/Linux/WSL**

### 1. Remove $AZULE environment variable and ~/Azule from your $PATH

For zsh and bash, open ~/.zprofile and ~/.profile respectively and remove the following:

```
# Azule
export AZULE=~/Azule

# add azule commands to path
if [ -d "$HOME/Azule" ] ; then
    PATH="$HOME/Azule:$PATH"
fi
```

For fish:
WIP

### 2. Delete the Azule repo
```
rm -rf ~/Azule
```

**Comment by nicknitewolf** [comment]
I don't know who in the right mind uses fish but you do you

**Review by Al4ise — CHANGES_REQUESTED** [review]
looks good in theory. I have some suggestions though:
1. running 'setup-azule' to update azule.. feels insanely odd. I think the name of the install script should be left as install as it feels more natural and less tedious compared to 'setup-azule'. Then we can have an allias called update-azule, also located in $AZULE, which we can then add to $PATH
2. The process of putting the executables in $PATH can be integrated into the installation script, improving on usability

**Comment by nicknitewolf** [comment]
> looks good in theory. I have some suggestions though:
> 
> 1. running 'setup-azule' to update azule.. feels insanely odd. I think the name of the install script should be left as install as it feels more natural and less tedious compared to 'setup-azule'. Then we can have an allias called update-azule, also located in $AZULE, which we can then add to $PATH

Fixed

> 2. The process of putting the executables in $PATH can be integrated into the installation script, improving on usability

Extremely hard to automate and / or prone to user failure if they have set-up their own bash profiles

**Pull request merged**
