### PR TITLE
fix: shellcheck azule-functions

### PR DESCRIPTION
**Pull request by nouun**
Quote all variables to prevent word splitting and globbing.

### CODE REVIEW

**Review by Al4ise — CHANGES_REQUESTED** [review]
Looks good! Just, could you put the mv commands on line 88 on separate lines?

**Comment by nouun** [comment]
Sorry, I didn't commit the azule file in the original push.

**Comment by Al4ise** [comment]
The things you did in azule-functions are nice but the things from azule... break a lot of things :/. There are many cases where I do want word splitting to happen

**Comment by nouun** [comment]
Would that be lines 821, 822, and 833?

**Comment by Al4ise** [comment]
More like 312, 416, 821, 822, 833 and 836

Also for 587, i’m not completely certain that *.ipa gets properly translated by the shell if it is inside the quotes. And I'm sorry if I'm being harsh, but the 'arguement' spelling is ok as is

**Comment by nouun** [comment]
I have reverted the last 2 commits.

For reference, re the "arguement" spelling, according to Oxford this is an obsolete spelling and is a rather common misspelling of "argument" but it isn't anything too important.

**Comment by Al4ise** [comment]
It's no big deal. Merging in a sec

**Pull request merged**
